version: '3.8'

services:
  dnp3-simulator:
    image: automatak/dnp3-simulator
    ports:
      - "20003:20000"
    environment:
      - DNP3_LOCAL_ADDRESS=10
      - DNP3_REMOTE_ADDRESS=1
    command: |
      sh -c "
        echo 'Starting DNP3 simulator with dummy data...'
        # Configure simulator with your target points
        # AI.008 = 255.0, AO.000 = 0.0 (zero value test)
        /usr/bin/dnp3-simulator --local-address=10 --remote-address=1 --port=20000 --ai-count=9 --ao-count=9
      "
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "20000"]
      interval: 30s
      timeout: 5s
      retries: 3
