device:
  name: "Vista-IoT-Gateway-001"
  model: "Vista-IoT-GW-5000"
  version: "2.1.0"
  location: ""
  description: ""

network:
  interfaces:
    eth0:
      type: "ethernet"
      enabled: true
      mode: "dhcp"
      link:
        speed: "auto"
        duplex: "auto"
      ipv4:
        mode: "dhcp"
        static:
          address: ""
          netmask: ""
          gateway: ""
        dns:
          primary: "8.8.8.8"
          secondary: "8.8.4.4"

protocols:
  modbus:
    enabled: true
    mode: "rtu"
    serial:
      port: "/dev/ttyUSB0"  # Default USB-to-RS485 port
      baudrate: 9600
      data_bits: 8
      parity: "N"
      stop_bits: 1
    slave_id: 1

logging:
  level: "info"
  max_size: "10M"
  max_files: 5
  remote_syslog:
    enabled: false
    server: ""
    port: 514

io_setup:
  ports: []  # Will be populated from database

communication_forward:
  destinations: []  # Will be populated from database
  bridges: []      # Will be populated from database 